# 22 ago 2018

Captura de dados (url das fotos) dos candidatos para as eleições 2018

In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
from utils.database_to_dataframe import database_to_dataframe

In [3]:
df_candidatos_2018 = database_to_dataframe(
    tabela='candidatura',
    colunas_tabela=['candidato_id', 'sequencial_candidato', 'sigla'],
    condicao='LEFT JOIN estado e on candidatura.estado_id = e.id WHERE eleicao_id = 202 OR eleicao_id = 203'
)

df_candidatos_2018

       candidato_id sequencial_candidato sigla
0           1261069          10000601020    AC
1            646217          10000608366    AC
2            968613          10000610671    AC
3            656527          10000602298    AC
4           1261070          10000607181    AC
5           1261071          10000600207    AC
6            401119          10000602510    AC
7           1261072          10000603909    AC
8               749          10000600242    AC
9            957338          10000602299    AC
10          1261073          10000610680    AC
11           968701          10000601172    AC
12          1261074          10000624308    AC
13           401323          10000608399    AC
14           657927          10000610694    AC
15          1261075          10000600118    AC
16           957518          10000608369    AC
17          1261076          10000600222    AC
18          1261077          10000602862    AC
19           968598          10000610674    AC
20          1261078          10000600124    AC
21           957332          10000610669    AC
22           957445          10000600798    AC
23          1261079          10000601163    AC
24          1261080          10000600245    AC
25           401193          10000624273    AC
26          1261081          10000600233    AC
27          1261082          10000602851    AC
28              982          10000608400    AC
29           414890          10000608367    AC
...             ...                  ...   ...
27857       1273351         270000625488    TO
27858        644642         270000625438    TO
27859        413929         270000626112    TO
27860       1257048         270000627130    TO
27861       1273352         270000621001    TO
27862       1273353         270000627752    TO
27863        643190         270000626124    TO
27864        968163         270000610948    TO
27865       1273354         270000610958    TO
27866        642211         270000610945    TO
27867       1273355         270000618838    TO
27868        398978         270000610924    TO
27869       1273356         270000620985    TO
27870       1273357         270000626130    TO
27871       1273358         270000627118    TO
27872       1273359         270000618818    TO
27873        414117         270000618865    TO
27874        968167         270000626099    TO
27875       1273360         270000625467    TO
27876       1273361         270000618846    TO
27877        642451         270000626128    TO
27878       1273362         270000627378    TO
27879       1273363         270000610968    TO
27880        656415         270000618842    TO
27881        398935         270000626126    TO
27882       1273364         270000626086    TO
27883       1273365         270000618874    TO
27884        954241         270000620986    TO
27885       1273366         270000627369    TO
27886        656403         270000610937    TO

[27887 rows x 3 columns]

In [4]:
df_candidatos_2018['sigla'] = df_candidatos_2018.sigla.fillna('BR').astype(str)

df_candidatos_2018

       candidato_id sequencial_candidato sigla
0           1261069          10000601020    AC
1            646217          10000608366    AC
2            968613          10000610671    AC
3            656527          10000602298    AC
4           1261070          10000607181    AC
5           1261071          10000600207    AC
6            401119          10000602510    AC
7           1261072          10000603909    AC
8               749          10000600242    AC
9            957338          10000602299    AC
10          1261073          10000610680    AC
11           968701          10000601172    AC
12          1261074          10000624308    AC
13           401323          10000608399    AC
14           657927          10000610694    AC
15          1261075          10000600118    AC
16           957518          10000608369    AC
17          1261076          10000600222    AC
18          1261077          10000602862    AC
19           968598          10000610674    AC
20          1261078          10000600124    AC
21           957332          10000610669    AC
22           957445          10000600798    AC
23          1261079          10000601163    AC
24          1261080          10000600245    AC
25           401193          10000624273    AC
26          1261081          10000600233    AC
27          1261082          10000602851    AC
28              982          10000608400    AC
29           414890          10000608367    AC
...             ...                  ...   ...
27857       1273351         270000625488    TO
27858        644642         270000625438    TO
27859        413929         270000626112    TO
27860       1257048         270000627130    TO
27861       1273352         270000621001    TO
27862       1273353         270000627752    TO
27863        643190         270000626124    TO
27864        968163         270000610948    TO
27865       1273354         270000610958    TO
27866        642211         270000610945    TO
27867       1273355         270000618838    TO
27868        398978         270000610924    TO
27869       1273356         270000620985    TO
27870       1273357         270000626130    TO
27871       1273358         270000627118    TO
27872       1273359         270000618818    TO
27873        414117         270000618865    TO
27874        968167         270000626099    TO
27875       1273360         270000625467    TO
27876       1273361         270000618846    TO
27877        642451         270000626128    TO
27878       1273362         270000627378    TO
27879       1273363         270000610968    TO
27880        656415         270000618842    TO
27881        398935         270000626126    TO
27882       1273364         270000626086    TO
27883       1273365         270000618874    TO
27884        954241         270000620986    TO
27885       1273366         270000627369    TO
27886        656403         270000610937    TO

[27887 rows x 3 columns]

In [5]:
df_candidatos_2018.iloc[14218]

candidato_id                 1267284
sequencial_candidato    180000613919
sigla                             PI
Name: 14218, dtype: object

In [8]:
request = requests.get(
    'http://divulgacandcontas.tse.jus.br/divulga/rest/v1/candidatura/buscar/2018/PI/2022802018/candidato/180000613919'
)

In [18]:
if not request.text:
    print('vazio')

vazio

In [20]:
request2 = requests.get(
    'http://divulgacandcontas.tse.jus.br/divulga/rest/v1/candidatura/buscar/2018/AC/2022802018/candidato/10000601020'
)

In [21]:
if not request2.text:
    print('vazio')

# Depois de ter rodado o script no terminal, vamos juntar os datasets gerados

In [3]:
df_candidatos_primeiros14200 = pd.read_csv(
    '../data/2018-08-22-tse-fotos-candidatos-2018-primeiros14200'
)

df_candidatos_primeiros14200

       candidato_id                                               foto
0           1261069  http://divulgacandcontas.tse.jus.br/candidatur...
1            646217  http://divulgacandcontas.tse.jus.br/candidatur...
2            968613  http://divulgacandcontas.tse.jus.br/candidatur...
3            656527  http://divulgacandcontas.tse.jus.br/candidatur...
4           1261070  http://divulgacandcontas.tse.jus.br/candidatur...
5           1261071  http://divulgacandcontas.tse.jus.br/candidatur...
6            401119  http://divulgacandcontas.tse.jus.br/candidatur...
7           1261072  http://divulgacandcontas.tse.jus.br/candidatur...
8               749  http://divulgacandcontas.tse.jus.br/candidatur...
9            957338  http://divulgacandcontas.tse.jus.br/candidatur...
10          1261073  http://divulgacandcontas.tse.jus.br/candidatur...
11           968701  http://divulgacandcontas.tse.jus.br/candidatur...
12          1261074  http://divulgacandcontas.tse.jus.br/candidatur...
13           401323  http://divulgacandcontas.tse.jus.br/candidatur...
14           657927  http://divulgacandcontas.tse.jus.br/candidatur...
15          1261075  http://divulgacandcontas.tse.jus.br/candidatur...
16           957518  http://divulgacandcontas.tse.jus.br/candidatur...
17          1261076  http://divulgacandcontas.tse.jus.br/candidatur...
18          1261077  http://divulgacandcontas.tse.jus.br/candidatur...
19           968598  http://divulgacandcontas.tse.jus.br/candidatur...
20          1261078  http://divulgacandcontas.tse.jus.br/candidatur...
21           957332  http://divulgacandcontas.tse.jus.br/candidatur...
22           957445  http://divulgacandcontas.tse.jus.br/candidatur...
23          1261079  http://divulgacandcontas.tse.jus.br/candidatur...
24          1261080  http://divulgacandcontas.tse.jus.br/candidatur...
25           401193  http://divulgacandcontas.tse.jus.br/candidatur...
26          1261081  http://divulgacandcontas.tse.jus.br/candidatur...
27          1261082  http://divulgacandcontas.tse.jus.br/candidatur...
28              982  http://divulgacandcontas.tse.jus.br/candidatur...
29           414890  http://divulgacandcontas.tse.jus.br/candidatur...
...             ...                                                ...
14170        817981  http://divulgacandcontas.tse.jus.br/candidatur...
14171        535613  http://divulgacandcontas.tse.jus.br/candidatur...
14172        407563  http://divulgacandcontas.tse.jus.br/candidatur...
14173        203519  http://divulgacandcontas.tse.jus.br/candidatur...
14174        212606  http://divulgacandcontas.tse.jus.br/candidatur...
14175       1267273  http://divulgacandcontas.tse.jus.br/candidatur...
14176       1118290  http://divulgacandcontas.tse.jus.br/candidatur...
14177       1121955  http://divulgacandcontas.tse.jus.br/candidatur...
14178        207483  http://divulgacandcontas.tse.jus.br/candidatur...
14179       1120198  http://divulgacandcontas.tse.jus.br/candidatur...
14180        810038  http://divulgacandcontas.tse.jus.br/candidatur...
14181        810782  http://divulgacandcontas.tse.jus.br/candidatur...
14182       1267274  http://divulgacandcontas.tse.jus.br/candidatur...
14183       1267275  http://divulgacandcontas.tse.jus.br/candidatur...
14184       1121654  http://divulgacandcontas.tse.jus.br/candidatur...
14185        535169  http://divulgacandcontas.tse.jus.br/candidatur...
14186       1118646  http://divulgacandcontas.tse.jus.br/candidatur...
14187       1267276  http://divulgacandcontas.tse.jus.br/candidatur...
14188        535225  http://divulgacandcontas.tse.jus.br/candidatur...
14189        208194  http://divulgacandcontas.tse.jus.br/candidatur...
14190        213511  http://divulgacandcontas.tse.jus.br/candidatur...
14191        407783  http://divulgacandcontas.tse.jus.br/candidatur...
14192       1125686  http://divulgacandcontas.tse.jus.br/candidatur...
14193       1267277  http://divulgacandcontas.tse.jus.br/candidatur...
14194       1267278  http://divulgacandcontas.tse.jus.br/candidatur...
14195       1118450  http://divulgacandcontas.tse.jus.br/candidatur...
14196       1267279  http://divulgacandcontas.tse.jus.br/candidatur...
14197        537603  http://divulgacandcontas.tse.jus.br/candidatur...
14198        205646  http://divulgacandcontas.tse.jus.br/candidatur...
14199       1267280  http://divulgacandcontas.tse.jus.br/candidatur...

[14200 rows x 2 columns]

In [4]:
df_candidatos_14200ateFim = pd.read_csv(
    '../data/2018-08-22-tse-fotos-candidatos-2018-14200ateFim'
)

df_candidatos_14200ateFim

       candidato_id                                               foto
0            407468  http://divulgacandcontas.tse.jus.br/candidatur...
1            205849  http://divulgacandcontas.tse.jus.br/candidatur...
2            213347  http://divulgacandcontas.tse.jus.br/candidatur...
3            536189  http://divulgacandcontas.tse.jus.br/candidatur...
4           1267281  http://divulgacandcontas.tse.jus.br/candidatur...
5           1132497  http://divulgacandcontas.tse.jus.br/candidatur...
6            963164  http://divulgacandcontas.tse.jus.br/candidatur...
7            963150  http://divulgacandcontas.tse.jus.br/candidatur...
8            541496  http://divulgacandcontas.tse.jus.br/candidatur...
9           1267282  http://divulgacandcontas.tse.jus.br/candidatur...
10          1267283  http://divulgacandcontas.tse.jus.br/candidatur...
11           225518  http://divulgacandcontas.tse.jus.br/candidatur...
12           222942  http://divulgacandcontas.tse.jus.br/candidatur...
13           218843  http://divulgacandcontas.tse.jus.br/candidatur...
14          1267284  http://divulgacandcontas.tse.jus.br/candidatur...
15           821930  http://divulgacandcontas.tse.jus.br/candidatur...
16          1130810  http://divulgacandcontas.tse.jus.br/candidatur...
17           819096  http://divulgacandcontas.tse.jus.br/candidatur...
18           218332  http://divulgacandcontas.tse.jus.br/candidatur...
19          1267285  http://divulgacandcontas.tse.jus.br/candidatur...
20           542642  http://divulgacandcontas.tse.jus.br/candidatur...
21          1267286  http://divulgacandcontas.tse.jus.br/candidatur...
22          1267287  http://divulgacandcontas.tse.jus.br/candidatur...
23           225359  http://divulgacandcontas.tse.jus.br/candidatur...
24           225373  http://divulgacandcontas.tse.jus.br/candidatur...
25           651351  http://divulgacandcontas.tse.jus.br/candidatur...
26           651369  http://divulgacandcontas.tse.jus.br/candidatur...
27          1267288  http://divulgacandcontas.tse.jus.br/candidatur...
28           225549  http://divulgacandcontas.tse.jus.br/candidatur...
29           223603  http://divulgacandcontas.tse.jus.br/candidatur...
...             ...                                                ...
13601       1273351  http://divulgacandcontas.tse.jus.br/candidatur...
13602        644642  http://divulgacandcontas.tse.jus.br/candidatur...
13603        413929  http://divulgacandcontas.tse.jus.br/candidatur...
13604       1257048  http://divulgacandcontas.tse.jus.br/candidatur...
13605       1273352  http://divulgacandcontas.tse.jus.br/candidatur...
13606       1273353  http://divulgacandcontas.tse.jus.br/candidatur...
13607        643190  http://divulgacandcontas.tse.jus.br/candidatur...
13608        968163  http://divulgacandcontas.tse.jus.br/candidatur...
13609       1273354  http://divulgacandcontas.tse.jus.br/candidatur...
13610        642211  http://divulgacandcontas.tse.jus.br/candidatur...
13611       1273355  http://divulgacandcontas.tse.jus.br/candidatur...
13612        398978  http://divulgacandcontas.tse.jus.br/candidatur...
13613       1273356  http://divulgacandcontas.tse.jus.br/candidatur...
13614       1273357  http://divulgacandcontas.tse.jus.br/candidatur...
13615       1273358  http://divulgacandcontas.tse.jus.br/candidatur...
13616       1273359  http://divulgacandcontas.tse.jus.br/candidatur...
13617        414117  http://divulgacandcontas.tse.jus.br/candidatur...
13618        968167  http://divulgacandcontas.tse.jus.br/candidatur...
13619       1273360  http://divulgacandcontas.tse.jus.br/candidatur...
13620       1273361  http://divulgacandcontas.tse.jus.br/candidatur...
13621        642451  http://divulgacandcontas.tse.jus.br/candidatur...
13622       1273362  http://divulgacandcontas.tse.jus.br/candidatur...
13623       1273363  http://divulgacandcontas.tse.jus.br/candidatur...
13624        656415  http://divulgacandcontas.tse.jus.br/candidatur...
13625        398935  http://divulgacandcontas.tse.jus.br/candidatur...
13626       1273364  http://divulgacandcontas.tse.jus.br/candidatur...
13627       1273365  http://divulgacandcontas.tse.jus.br/candidatur...
13628        954241  http://divulgacandcontas.tse.jus.br/candidatur...
13629       1273366  http://divulgacandcontas.tse.jus.br/candidatur...
13630        656403  http://divulgacandcontas.tse.jus.br/candidatur...

[13631 rows x 2 columns]

In [5]:
df_fotos = df_candidatos_primeiros14200.append(df_candidatos_14200ateFim)

df_fotos

       candidato_id                                               foto
0           1261069  http://divulgacandcontas.tse.jus.br/candidatur...
1            646217  http://divulgacandcontas.tse.jus.br/candidatur...
2            968613  http://divulgacandcontas.tse.jus.br/candidatur...
3            656527  http://divulgacandcontas.tse.jus.br/candidatur...
4           1261070  http://divulgacandcontas.tse.jus.br/candidatur...
5           1261071  http://divulgacandcontas.tse.jus.br/candidatur...
6            401119  http://divulgacandcontas.tse.jus.br/candidatur...
7           1261072  http://divulgacandcontas.tse.jus.br/candidatur...
8               749  http://divulgacandcontas.tse.jus.br/candidatur...
9            957338  http://divulgacandcontas.tse.jus.br/candidatur...
10          1261073  http://divulgacandcontas.tse.jus.br/candidatur...
11           968701  http://divulgacandcontas.tse.jus.br/candidatur...
12          1261074  http://divulgacandcontas.tse.jus.br/candidatur...
13           401323  http://divulgacandcontas.tse.jus.br/candidatur...
14           657927  http://divulgacandcontas.tse.jus.br/candidatur...
15          1261075  http://divulgacandcontas.tse.jus.br/candidatur...
16           957518  http://divulgacandcontas.tse.jus.br/candidatur...
17          1261076  http://divulgacandcontas.tse.jus.br/candidatur...
18          1261077  http://divulgacandcontas.tse.jus.br/candidatur...
19           968598  http://divulgacandcontas.tse.jus.br/candidatur...
20          1261078  http://divulgacandcontas.tse.jus.br/candidatur...
21           957332  http://divulgacandcontas.tse.jus.br/candidatur...
22           957445  http://divulgacandcontas.tse.jus.br/candidatur...
23          1261079  http://divulgacandcontas.tse.jus.br/candidatur...
24          1261080  http://divulgacandcontas.tse.jus.br/candidatur...
25           401193  http://divulgacandcontas.tse.jus.br/candidatur...
26          1261081  http://divulgacandcontas.tse.jus.br/candidatur...
27          1261082  http://divulgacandcontas.tse.jus.br/candidatur...
28              982  http://divulgacandcontas.tse.jus.br/candidatur...
29           414890  http://divulgacandcontas.tse.jus.br/candidatur...
...             ...                                                ...
13601       1273351  http://divulgacandcontas.tse.jus.br/candidatur...
13602        644642  http://divulgacandcontas.tse.jus.br/candidatur...
13603        413929  http://divulgacandcontas.tse.jus.br/candidatur...
13604       1257048  http://divulgacandcontas.tse.jus.br/candidatur...
13605       1273352  http://divulgacandcontas.tse.jus.br/candidatur...
13606       1273353  http://divulgacandcontas.tse.jus.br/candidatur...
13607        643190  http://divulgacandcontas.tse.jus.br/candidatur...
13608        968163  http://divulgacandcontas.tse.jus.br/candidatur...
13609       1273354  http://divulgacandcontas.tse.jus.br/candidatur...
13610        642211  http://divulgacandcontas.tse.jus.br/candidatur...
13611       1273355  http://divulgacandcontas.tse.jus.br/candidatur...
13612        398978  http://divulgacandcontas.tse.jus.br/candidatur...
13613       1273356  http://divulgacandcontas.tse.jus.br/candidatur...
13614       1273357  http://divulgacandcontas.tse.jus.br/candidatur...
13615       1273358  http://divulgacandcontas.tse.jus.br/candidatur...
13616       1273359  http://divulgacandcontas.tse.jus.br/candidatur...
13617        414117  http://divulgacandcontas.tse.jus.br/candidatur...
13618        968167  http://divulgacandcontas.tse.jus.br/candidatur...
13619       1273360  http://divulgacandcontas.tse.jus.br/candidatur...
13620       1273361  http://divulgacandcontas.tse.jus.br/candidatur...
13621        642451  http://divulgacandcontas.tse.jus.br/candidatur...
13622       1273362  http://divulgacandcontas.tse.jus.br/candidatur...
13623       1273363  http://divulgacandcontas.tse.jus.br/candidatur...
13624        656415  http://divulgacandcontas.tse.jus.br/candidatur...
13625        398935  http://divulgacandcontas.tse.jus.br/candidatur...
13626       1273364  http://divulgacandcontas.tse.jus.br/candidatur...
13627       1273365  http://divulgacandcontas.tse.jus.br/candidatur...
13628        954241  http://divulgacandcontas.tse.jus.br/candidatur...
13629       1273366  http://divulgacandcontas.tse.jus.br/candidatur...
13630        656403  http://divulgacandcontas.tse.jus.br/candidatur...

[27831 rows x 2 columns]

## Migrar Dados 2018 Atualizados

In [6]:
from utils.tse_migrar_dados_por_estado_2018 import migrar_dados

In [7]:
migrar_dados(2018)

Iniciando ../temp\consulta_cand_2018_AC.csv
Total de candidaturas em 2018: 567
567 de 567
Tempo total desse estado: 5.60s

Iniciando ../temp\consulta_cand_2018_AL.csv
Total de candidaturas em 2018: 415
415 de 415
Tempo total desse estado: 3.99s

Iniciando ../temp\consulta_cand_2018_AM.csv
Total de candidaturas em 2018: 828
828 de 828
Tempo total desse estado: 7.84s

Iniciando ../temp\consulta_cand_2018_AP.csv
Total de candidaturas em 2018: 653
653 de 653
Tempo total desse estado: 5.80s

Iniciando ../temp\consulta_cand_2018_BA.csv
Total de candidaturas em 2018: 1124
1124 de 1124
Tempo total desse estado: 11.31s

Iniciando ../temp\consulta_cand_2018_BR.csv
Total de candidaturas em 2018: 26
26 de 26
Tempo total desse estado: 0.31s

Iniciando ../temp\consulta_cand_2018_CE.csv
Total de candidaturas em 2018: 900
900 de 900
Tempo total desse estado: 8.47s

Iniciando ../temp\consulta_cand_2018_DF.csv
Total de candidaturas em 2018: 1215
1215 de 1215
Tempo total desse estado: 10.26s

Iniciando ../temp\consulta_cand_2018_ES.csv
Total de candidaturas em 2018: 807
807 de 807
Tempo total desse estado: 7.61s

Iniciando ../temp\consulta_cand_2018_GO.csv
Total de candidaturas em 2018: 1124
1124 de 1124
Tempo total desse estado: 10.96s

Iniciando ../temp\consulta_cand_2018_MA.csv
Total de candidaturas em 2018: 714
714 de 714
Tempo total desse estado: 6.58s

Iniciando ../temp\consulta_cand_2018_MG.csv
Total de candidaturas em 2018: 2266
2266 de 2266
Tempo total desse estado: 24.54s

Iniciando ../temp\consulta_cand_2018_MS.csv
Total de candidaturas em 2018: 523
523 de 523
Tempo total desse estado: 4.74s

Iniciando ../temp\consulta_cand_2018_MT.csv
Total de candidaturas em 2018: 525
525 de 525
Tempo total desse estado: 4.96s

Iniciando ../temp\consulta_cand_2018_PA.csv
Total de candidaturas em 2018: 856
856 de 856
Tempo total desse estado: 8.26s

Iniciando ../temp\consulta_cand_2018_PB.csv
Total de candidaturas em 2018: 601
601 de 601
Tempo total desse estado: 5.71s

Iniciando ../temp\consulta_cand_2018_PE.csv
Total de candidaturas em 2018: 1060
1060 de 1060
Tempo total desse estado: 10.11s

Iniciando ../temp\consulta_cand_2018_PI.csv
Total de candidaturas em 2018: 472
472 de 472
Tempo total desse estado: 4.33s

Iniciando ../temp\consulta_cand_2018_PR.csv
Total de candidaturas em 2018: 1236
1236 de 1236
Tempo total desse estado: 12.51s

Iniciando ../temp\consulta_cand_2018_RJ.csv
Total de candidaturas em 2018: 3524
3524 de 3524
Tempo total desse estado: 32.30s

Iniciando ../temp\consulta_cand_2018_RN.csv
Total de candidaturas em 2018: 488
488 de 488
Tempo total desse estado: 4.61s

Iniciando ../temp\consulta_cand_2018_RO.csv
Total de candidaturas em 2018: 582
582 de 582
Tempo total desse estado: 5.22s

Iniciando ../temp\consulta_cand_2018_RR.csv
Total de candidaturas em 2018: 652
652 de 652
Tempo total desse estado: 8.92s

Iniciando ../temp\consulta_cand_2018_RS.csv
Total de candidaturas em 2018: 1300
1300 de 1300
Tempo total desse estado: 13.03s

Iniciando ../temp\consulta_cand_2018_SC.csv
Total de candidaturas em 2018: 765
765 de 765
Tempo total desse estado: 7.32s

Iniciando ../temp\consulta_cand_2018_SE.csv
Total de candidaturas em 2018: 500
500 de 500
Tempo total desse estado: 4.34s

Iniciando ../temp\consulta_cand_2018_SP.csv
Total de candidaturas em 2018: 3823
3823 de 3823
Tempo total desse estado: 38.93s

Iniciando ../temp\consulta_cand_2018_TO.csv
Total de candidaturas em 2018: 341
341 de 341
Tempo total desse estado: 3.48s

Iniciando ../temp\consulta_cand_2018_ZZ.csv
Total de candidaturas em 2018: 0

Tempo total desse estado: 0.02s

Tempo total em 2018: 272.11s

## Atualizar Fotos no Banco de Dados

In [8]:
import sys
import mysql.connector as mysql

BD_CONFIG = {
    'user': 'root',
    'password': '',
    'host': '127.0.0.1',
    'database': 'laddres'
}

In [18]:
cnx = mysql.connect(**BD_CONFIG)
cursor = cnx.cursor()

total = len(df_fotos)
for candidato in df_fotos.itertuples():
    sys.stdout.write('\r{} de {}'.format(candidato.Index, total))
    sys.stdout.flush()

#     query = 'UPDATE candidato SET foto = "{}" WHERE id = {}'.format(candidato.foto, candidato.candidato_id)
#     query = 'UPDATE candidato SET foto = %s WHERE id = %s'
    query = (
        "UPDATE candidato "
        "SET "
        "foto = %(foto)s "
        "WHERE id = %(candidato_id)s"
    )
    atributos = {
        'foto': candidato.foto,
        'candidato_id': candidato.candidato_id
    }

    try:
#         cursor.execute(query, (candidato.foto, candidato.candidato_id))
        cursor.execute(query, atributos)
        cnx.commit()
    except:
        print(candidato)
        cursor.close()
        cnx.close()
        raise

cursor.close()
cnx.close()

13630 de 27831